[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { }

[environments.production.services.web]
source = "."
build = { builder = "DOCKERFILE" }
deploy = {
  healthcheckPath = "/health",
  healthcheckTimeout = 300,
  restartPolicyType = "ON_FAILURE"
}

[environments.production.services.database]
source = "mysql:8"
variables = {
  MYSQL_DATABASE = "railway",
  MYSQL_ROOT_PASSWORD = { generate = true }
}
