version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    port: 8080
    env:
      APP_ENV: production
      APP_DEBUG: false
      SESSION_DRIVER: database
      CACHE_DRIVER: database
      QUEUE_CONNECTION: database
    healthCheck:
      path: /health
      initialDelay: 30
      timeout: 10
      interval: 30
